import Head from 'next/head'
import Image from 'next/image'
import Button from '../components/Button/Button'
import Input from '../components/Input/Input'
import SelectOption from '../components/SelectOption/SelectOption'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
          crossorigin="anonymous"
        />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Button
          label={"Press Me"}
          backgroundColor={"blue"}
          isRounded={true}
          handleClick={() => { alert('onClick handle') }}
        />
        <SelectOption value={{ value: 'vanilla', label: 'Vanilla' }} />
        <Input title="Judul" label="abc" type="text" placeholder="bcd" />
      </div>


    </div>
  )
}
